
exe		=	a.out
ppp_sources	=	ppp/std_lib_facilities.h

#source		=	1_pointer_output_format.cpp
#source		=	2_sizes_of_types.cpp
#source		=	3_to_lower.cpp
#source		=	4_copy_string.cpp
#source		=	5_findx_substring.cpp
#source		=	6_memory_exhaustion.cpp
#source		=	7_read_input_in_array.cpp
#source		=	8_read_input_in_std_string.cpp
#source		=	9_stack_grow_direction.cpp
#source		=	link_trial.cpp
#source		=	11_list_of_gods.cpp
#source		=	13_list_of_god_structs.cpp
source		=	14_list_of_gods_singly_linked_list.cpp


a.out:	$(source) $(ppp_sources)
	g++ -std=c++14 -o $(exe) -Wall $(source) $(ppp_sources)

clean:
	@rm -f $(exe)
